server:
  port: 9091
spring:
  application:
    name: microservice-custom-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:9051/eureka/
  instance:
    prefer-ip-address: true
